const QUESTIONS = [
    // Historia
    { category: "Historia", question: "Berlinmuren föll", answer: 1989, hint: "Kalla krigets slut närmade sig" },
    { category: "Historia", question: "Franska revolutionen började", answer: 1789, hint: "Stormningen av Bastiljen" },
    { category: "Historia", question: "Titanic sjönk", answer: 1912, hint: "Det 'osänkbara' skeppet" },
    { category: "Historia", question: "Första världskriget slutade", answer: 1918, hint: "Den 11:e timmen, den 11:e dagen, den 11:e månaden" },
    { category: "Historia", question: "Neil Armstrong gick på månen", answer: 1969, hint: "Ett litet steg för en människa..." },
    { category: "Historia", question: "Amerikas förenta stater grundades", answer: 1776, hint: "Independence Day" },
    { category: "Historia", question: "Andra världskriget slutade", answer: 1945, hint: "Atombomber över Japan" },
    { category: "Historia", question: "Kristofer Columbus nådde Amerika", answer: 1492, hint: "Han trodde han var i Indien" },
    { category: "Historia", question: "Stockholms blodbad ägde rum", answer: 1520, hint: "Kristian II avrättade svenska adelsmän" },
    { category: "Historia", question: "Gustav Vasa blev kung av Sverige", answer: 1523, hint: "Sveriges nationaldag firas till hans ära" },
    { category: "Historia", question: "Mordet på Martin Luther King Jr.", answer: 1968, hint: "I have a dream" },
    { category: "Historia", question: "Napoleon Bonaparte blev kejsare av Frankrike", answer: 1804, hint: "Han krönte sig själv" },
    { category: "Historia", question: "Den stora branden i London", answer: 1666, hint: "Började i ett bageri" },

    // Vetenskap & Teknik
    { category: "Vetenskap", question: "Den första iPhonen lanserades", answer: 2007, hint: "Steve Jobs stod på scenen" },
    { category: "Vetenskap", question: "World Wide Web uppfanns", answer: 1989, hint: "Tim Berners-Lee vid CERN" },
    { category: "Vetenskap", question: "DNA-strukturen upptäcktes", answer: 1953, hint: "Watson och Crick" },
    { category: "Vetenskap", question: "Första e-postmeddelandet skickades", answer: 1971, hint: "Ray Tomlinson använde @-tecknet" },
    { category: "Vetenskap", question: "Google grundades", answer: 1998, hint: "Startade i ett garage i Kalifornien" },
    { category: "Vetenskap", question: "Penicillin upptäcktes", answer: 1928, hint: "Alexander Fleming glömde en petriskål" },
    { category: "Vetenskap", question: "Facebook lanserades", answer: 2004, hint: "Mark Zuckerberg var på Harvard" },
    { category: "Vetenskap", question: "Glödlampan uppfanns", answer: 1879, hint: "Thomas Edison" },
    { category: "Vetenskap", question: "Första kommersiella mobiltelefonen såldes", answer: 1983, hint: "Motorola DynaTAC, vägde nästan 1 kg" },
    { category: "Vetenskap", question: "Wikipedia grundades", answer: 2001, hint: "Fri kunskap för alla" },
    { category: "Vetenskap", question: "Spotify lanserades", answer: 2008, hint: "Svenskt musikföretag" },
    { category: "Vetenskap", question: "Dynamit uppfanns", answer: 1867, hint: "Alfred Nobel" },

    // Sport
    { category: "Sport", question: "Sverige vann OS-guld i fotboll", answer: 1948, hint: "Sommar-OS i London" },
    { category: "Sport", question: "Björn Borg vann sin första Wimbledon-titel", answer: 1976, hint: "Svensk tennislegend" },
    { category: "Sport", question: "Zlatan Ibrahimovic debuterade i landslaget", answer: 2001, hint: "Mot Färöarna" },
    { category: "Sport", question: "Första moderna olympiska spelen hölls", answer: 1896, hint: "I Aten, Grekland" },
    { category: "Sport", question: "Sverige blev VM-tvåa i fotboll på hemmaplan", answer: 1958, hint: "Brasilien vann med Pelé" },
    { category: "Sport", question: "Ingemar Stenmark vann sina OS-guld", answer: 1980, hint: "Lake Placid" },
    { category: "Sport", question: "Tre Kronor vann OS-guld i ishockey för första gången", answer: 1994, hint: "Lillehammer, Norge" },
    { category: "Sport", question: "Usain Bolt satte världsrekord på 100 meter", answer: 2009, hint: "9,58 sekunder i Berlin" },
    { category: "Sport", question: "Första Super Bowl spelades", answer: 1967, hint: "Green Bay Packers vann" },
    { category: "Sport", question: "Carolina Klüft vann OS-guld i sjukamp", answer: 2004, hint: "Aten, Grekland" },

    // Kultur & Nöje
    { category: "Kultur", question: "ABBA vann Eurovision Song Contest", answer: 1974, hint: "Waterloo!" },
    { category: "Kultur", question: "Första Star Wars-filmen hade premiär", answer: 1977, hint: "A long time ago in a galaxy far, far away..." },
    { category: "Kultur", question: "Minecraft släpptes", answer: 2011, hint: "Markus 'Notch' Persson" },
    { category: "Kultur", question: "Beatles splittrades", answer: 1970, hint: "Let It Be var deras sista album" },
    { category: "Kultur", question: "Första Harry Potter-boken publicerades", answer: 1997, hint: "J.K. Rowling" },
    { category: "Kultur", question: "Astrid Lindgren publicerade Pippi Långstrump", answer: 1945, hint: "Världens starkaste flicka" },
    { category: "Kultur", question: "Netflix startade sin streamingtjänst", answer: 2007, hint: "Från DVD-uthyrning till streaming" },
    { category: "Kultur", question: "Första Melodifestivalen i Sverige hölls", answer: 1959, hint: "Svensk musiktradition" },
    { category: "Kultur", question: "Mona Lisa stals från Louvren", answer: 1911, hint: "En italiensk hantverkare tog den" },
    { category: "Kultur", question: "TikTok lanserades internationellt", answer: 2017, hint: "Kort videoformat från Kina" },
    { category: "Kultur", question: "Hobbit av J.R.R. Tolkien publicerades", answer: 1937, hint: "I ett hål i marken bodde en hobbit" },

    // Sverige
    { category: "Sverige", question: "Sverige gick med i EU", answer: 1995, hint: "Folkomröstning året innan" },
    { category: "Sverige", question: "Mordet på Olof Palme", answer: 1986, hint: "På Sveavägen i Stockholm" },
    { category: "Sverige", question: "Kvinnor fick rösträtt i Sverige", answer: 1921, hint: "Första valet med kvinnlig rösträtt" },
    { category: "Sverige", question: "Sverige bytte till högertrafik", answer: 1967, hint: "Dagen H - den 3 september" },
    { category: "Sverige", question: "Tsunamikatastrofen som drabbade svenskar", answer: 2004, hint: "Sydostasien, annandag jul" },
    { category: "Sverige", question: "Kronprinsessan Victoria gifte sig", answer: 2010, hint: "Med Daniel Westling" },
    { category: "Sverige", question: "IKEA grundades", answer: 1943, hint: "Ingvar Kamprad var 17 år" },
    { category: "Sverige", question: "Regalskeppet Vasa sjönk", answer: 1628, hint: "På sin jungfruresa i Stockholms hamn" },
    { category: "Sverige", question: "Alfred Nobel instiftade Nobelpriset i sitt testamente", answer: 1895, hint: "Året innan han dog" },
    { category: "Sverige", question: "Öresundsbron invigdes", answer: 2000, hint: "Förbinder Sverige och Danmark" },
    { category: "Sverige", question: "Estonia-katastrofen", answer: 1994, hint: "Färjan sjönk på Östersjön" },
    { category: "Sverige", question: "Volvo grundades i Göteborg", answer: 1927, hint: "Säkerhet i fokus" },

    // Dator/TV-spel
    { category: "Spel", question: "Pong släpptes av Atari", answer: 1972, hint: "Ett av de allra första TV-spelen" },
    { category: "Spel", question: "Super Mario Bros släpptes till NES", answer: 1985, hint: "Nintendos ikoniska rörmokare" },
    { category: "Spel", question: "Tetris skapades", answer: 1984, hint: "Av en rysk programmerare" },
    { category: "Spel", question: "PlayStation 1 lanserades i Japan", answer: 1994, hint: "Sonys första konsol" },
    { category: "Spel", question: "World of Warcraft släpptes", answer: 2004, hint: "Blizzards MMORPG" },
    { category: "Spel", question: "Pokémon Red och Blue släpptes i Japan", answer: 1996, hint: "Gotta catch 'em all!" },
    { category: "Spel", question: "Grand Theft Auto V släpptes", answer: 2013, hint: "Rockstar Games mest sålda spel" },
    { category: "Spel", question: "The Legend of Zelda: Ocarina of Time släpptes", answer: 1998, hint: "Ofta kallat bästa spelet någonsin" },
    { category: "Spel", question: "Fortnite Battle Royale lanserades", answer: 2017, hint: "Epic Games gratisspel" },
    { category: "Spel", question: "Minecraft skapades av Notch", answer: 2009, hint: "Första versionen hette Cave Game" },
    { category: "Spel", question: "Halo: Combat Evolved släpptes", answer: 2001, hint: "Xboxens flaggskepp" },
    { category: "Spel", question: "Nintendo 64 lanserades", answer: 1996, hint: "Nintendos första 3D-konsol" },
    { category: "Spel", question: "Doom släpptes", answer: 1993, hint: "FPS-genrens genombrott" },
    { category: "Spel", question: "Xbox 360 lanserades", answer: 2005, hint: "Microsofts andra konsol" },
    { category: "Spel", question: "Among Us blev viralt", answer: 2020, hint: "Vem är bedragaren?" },
    { category: "Spel", question: "Roblox lanserades", answer: 2006, hint: "Plattform där spelare skapar spel" },
    { category: "Spel", question: "Elden Ring släpptes", answer: 2022, hint: "FromSoftware + George R.R. Martin" },
    { category: "Spel", question: "Nintendo Switch lanserades", answer: 2017, hint: "Hybrid mellan hemma- och portabel konsol" },
    { category: "Spel", question: "Game Boy lanserades", answer: 1989, hint: "Nintendos portabla konsol med Tetris" },
    { category: "Spel", question: "The Sims släpptes", answer: 2000, hint: "Maxis livssimulator" },

    // Anime
    { category: "Anime", question: "Dragon Ball Z började sändas", answer: 1989, hint: "Goku blir Super Saiyan" },
    { category: "Anime", question: "Naruto-mangan började publiceras", answer: 1999, hint: "Ninjavägen till Hokage" },
    { category: "Anime", question: "One Piece-mangan startade", answer: 1997, hint: "Monkey D. Luffy letar efter skatten" },
    { category: "Anime", question: "Attack on Titan anime hade premiär", answer: 2013, hint: "Titaner attackerar mänskligheten" },
    { category: "Anime", question: "Studio Ghibli grundades", answer: 1985, hint: "Hayao Miyazakis studio" },
    { category: "Anime", question: "Spirited Away hade biopremiär", answer: 2001, hint: "Vann Oscar för bästa animerade film" },
    { category: "Anime", question: "Death Note anime hade premiär", answer: 2006, hint: "En anteckningsbok som dödar" },
    { category: "Anime", question: "Neon Genesis Evangelion hade premiär", answer: 1995, hint: "Shinji, stig in i roboten!" },
    { category: "Anime", question: "Akira hade biopremiär", answer: 1988, hint: "Cyberpunk-klassiker i Neo-Tokyo" },
    { category: "Anime", question: "Pokémon-animen hade premiär i Japan", answer: 1997, hint: "Ash och Pikachu" },
    { category: "Anime", question: "My Hero Academia anime hade premiär", answer: 2016, hint: "Plus Ultra!" },
    { category: "Anime", question: "Demon Slayer anime hade premiär", answer: 2019, hint: "Tanjiro jagar demoner" },
    { category: "Anime", question: "Sailor Moon hade premiär", answer: 1992, hint: "I månens namn ska jag straffa dig!" },
    { category: "Anime", question: "Your Name hade biopremiär", answer: 2016, hint: "Makoto Shinkais storfilm" },
    { category: "Anime", question: "Cowboy Bebop hade premiär", answer: 1998, hint: "See you space cowboy..." },
    { category: "Anime", question: "Jujutsu Kaisen anime hade premiär", answer: 2020, hint: "Yuji Itadori sväljer Sukunas finger" },
    { category: "Anime", question: "Fullmetal Alchemist Brotherhood hade premiär", answer: 2009, hint: "Bröderna Elric söker de vises sten" },
    { category: "Anime", question: "Dragon Ball-mangan började publiceras", answer: 1984, hint: "Akira Toriyama skapade Son Goku" },

    // Filmer
    { category: "Filmer", question: "Titanic hade biopremiär", answer: 1997, hint: "Leonardo DiCaprio och Kate Winslet" },
    { category: "Filmer", question: "The Matrix hade premiär", answer: 1999, hint: "Red pill or blue pill?" },
    { category: "Filmer", question: "Jurassic Park hade premiär", answer: 1993, hint: "Spielbergs dinosaurier" },
    { category: "Filmer", question: "The Lord of the Rings: Fellowship of the Ring hade premiär", answer: 2001, hint: "Peter Jacksons epos" },
    { category: "Filmer", question: "Avengers: Endgame hade premiär", answer: 2019, hint: "Avengers assemble!" },
    { category: "Filmer", question: "The Dark Knight hade premiär", answer: 2008, hint: "Heath Ledgers Joker" },
    { category: "Filmer", question: "Inception hade premiär", answer: 2010, hint: "En dröm i en dröm" },
    { category: "Filmer", question: "Pulp Fiction hade premiär", answer: 1994, hint: "Quentin Tarantino" },
    { category: "Filmer", question: "Forrest Gump hade premiär", answer: 1994, hint: "Livet är som en ask choklad" },
    { category: "Filmer", question: "E.T. hade biopremiär", answer: 1982, hint: "Phone home!" },
    { category: "Filmer", question: "Jaws hade premiär", answer: 1975, hint: "Spielbergs hajfilm" },
    { category: "Filmer", question: "Frozen hade premiär", answer: 2013, hint: "Let it go!" },
    { category: "Filmer", question: "Iron Man hade premiär (MCU startade)", answer: 2008, hint: "Robert Downey Jr. som Tony Stark" },
    { category: "Filmer", question: "Avatar hade biopremiär", answer: 2009, hint: "James Camerons blåa värld" },
    { category: "Filmer", question: "Back to the Future hade premiär", answer: 1985, hint: "Marty McFly och Doc Brown" },
    { category: "Filmer", question: "The Godfather hade premiär", answer: 1972, hint: "Ett erbjudande han inte kan tacka nej till" },
    { category: "Filmer", question: "Toy Story hade premiär", answer: 1995, hint: "Pixars första film" },
    { category: "Filmer", question: "Gladiator hade premiär", answer: 2000, hint: "Russell Crowe i Colosseum" },

    // Serier
    { category: "Serier", question: "Friends hade premiär", answer: 1994, hint: "I'll be there for you" },
    { category: "Serier", question: "Game of Thrones hade premiär", answer: 2011, hint: "Winter is coming" },
    { category: "Serier", question: "Breaking Bad hade premiär", answer: 2008, hint: "Kemilärare blir drogkung" },
    { category: "Serier", question: "The Simpsons hade premiär", answer: 1989, hint: "D'oh!" },
    { category: "Serier", question: "Stranger Things hade premiär", answer: 2016, hint: "Upside Down i Hawkins" },
    { category: "Serier", question: "The Office (US) hade premiär", answer: 2005, hint: "That's what she said" },
    { category: "Serier", question: "Lost hade premiär", answer: 2004, hint: "En flygkrasch på en mystisk ö" },
    { category: "Serier", question: "The Walking Dead hade premiär", answer: 2010, hint: "Zombieapokalyps" },
    { category: "Serier", question: "Squid Game hade premiär", answer: 2021, hint: "Koreansk överlevnadsserie på Netflix" },
    { category: "Serier", question: "The Mandalorian hade premiär", answer: 2019, hint: "This is the way" },
    { category: "Serier", question: "Seinfeld hade premiär", answer: 1989, hint: "Serien om ingenting" },
    { category: "Serier", question: "The Sopranos hade premiär", answer: 1999, hint: "Tony Soprano och maffian" },
    { category: "Serier", question: "Peaky Blinders hade premiär", answer: 2013, hint: "Gangsters i Birmingham" },
    { category: "Serier", question: "Wednesday hade premiär", answer: 2022, hint: "Addams Family på Netflix" },
    { category: "Serier", question: "The Witcher hade premiär", answer: 2019, hint: "Henry Cavill som Geralt" },
    { category: "Serier", question: "Rick and Morty hade premiär", answer: 2013, hint: "Wubba lubba dub dub!" },
    { category: "Serier", question: "South Park hade premiär", answer: 1997, hint: "Oh my God, they killed Kenny!" },
    { category: "Serier", question: "House of the Dragon hade premiär", answer: 2022, hint: "Game of Thrones prequel" }
];

const CATEGORIES = [...new Set(QUESTIONS.map(q => q.category))];
