// Image-based questions for all categories
// Uses free image sources: flagcdn (flags), imgflip (memes), unsplash (photos)

const IMAGE_QUESTIONS = [
    // === MEMES ===
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/1bij.jpg",
      options: ["Distracted Boyfriend", "Jealous Girlfriend", "Love Triangle", "Caught Looking", "Guy Looking Back", "Unfaithful Dude", "The Wandering Eye", "Boyfriend Meme"],
      answer: "Distracted Boyfriend" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/30b1gx.jpg",
      options: ["Woman Yelling at Cat", "Angry Lady and Cat", "Cat at Dinner Table", "Screaming Woman Cat", "Karen vs Cat", "The Dinner Argument", "Confused Cat Meme", "Lady Shouts at Cat"],
      answer: "Woman Yelling at Cat" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/1g8my4.jpg",
      options: ["This Is Fine", "Everything Is Fine", "Fire Dog", "Dog in Fire", "It's All Good", "Burning Room Dog", "Fine Meme", "Calm Dog Fire"],
      answer: "This Is Fine" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/9ehk.jpg",
      options: ["Roll Safe", "Thinking Black Guy", "Smart Move", "Big Brain Time", "Clever Man", "Can't Fail If...", "Hood Think", "The Thinker Meme"],
      answer: "Roll Safe" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/1otk96.jpg",
      options: ["Is This a Pigeon?", "Butterfly Man", "What Is This?", "Confused Anime Guy", "Is This a Bird?", "Anime Butterfly", "Clueless Guy Meme", "The Butterfly Question"],
      answer: "Is This a Pigeon?" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/1ur9b0.jpg",
      options: ["Change My Mind", "Prove Me Wrong", "Debate Me", "The Table Guy", "Crowder Meme", "Fight Me On This", "Coffee Debate", "Steven Crowder"],
      answer: "Change My Mind" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/26am.jpg",
      options: ["One Does Not Simply", "Boromir Meme", "Lord of the Memes", "You Cannot Simply", "It's Not That Easy", "Walk Into Mordor", "Sean Bean Explains", "Simply Not Done"],
      answer: "One Does Not Simply" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/4t0m5.jpg",
      options: ["Drake Hotline Bling", "Drake Yes No", "Drake Approves", "Drake Choose", "Hotline Drake", "Drake Pointing", "Drake Decision", "Drake Prefer"],
      answer: "Drake Hotline Bling" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/2fm6x.jpg",
      options: ["Mocking SpongeBob", "SpongeBob Chicken", "Sarcastic SpongeBob", "Weird SpongeBob", "tHiS mEmE", "SpongeBob Roast", "SpongeBob Sass", "Derpy SpongeBob"],
      answer: "Mocking SpongeBob" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/3lmzyx.jpg",
      options: ["Stonks", "Stocks Meme", "Meme Man Stonks", "Business Meme", "Surreal Trader", "Not Stonks", "Profit Man", "Meme Man Finance"],
      answer: "Stonks" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/1h7in3.jpg",
      options: ["Expanding Brain", "Galaxy Brain", "Big Brain", "Brain Levels", "Mind Blown", "Brain Evolution", "Ascended Brain", "Enlightened Mind"],
      answer: "Expanding Brain" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/21aqbc.jpg",
      options: ["Surprised Pikachu", "Shocked Pikachu", "Pikachu Face", "Open Mouth Pikachu", "Pikachu Gasp", "Stunned Pikachu", "OMG Pikachu", "Pikachu Meme"],
      answer: "Surprised Pikachu" },
    { category: "Memes", question: "Vad heter denna meme?", image: "https://i.imgflip.com/24y43o.jpg",
      options: ["Gru's Plan", "Despicable Plan", "Gru Presentation", "Minion Boss Plan", "Evil Plan Fail", "Gru Whiteboard", "Gru's Mistake", "The Gru Meme"],
      answer: "Gru's Plan" },

    // === FLAGGOR ===
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/jp.png",
      options: ["Japan", "Kina", "Sydkorea", "Bangladesh"], answer: "Japan" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/br.png",
      options: ["Brasilien", "Portugal", "Mexiko", "Argentina"], answer: "Brasilien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ca.png",
      options: ["Kanada", "Peru", "Japan", "Schweiz"], answer: "Kanada" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/za.png",
      options: ["Sydafrika", "Ghana", "Kenya", "Etiopien"], answer: "Sydafrika" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/kr.png",
      options: ["Sydkorea", "Japan", "Taiwan", "Nordkorea"], answer: "Sydkorea" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/mx.png",
      options: ["Mexiko", "Italien", "Irland", "Ungern"], answer: "Mexiko" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/in.png",
      options: ["Indien", "Irland", "Elfenbenskusten", "Niger"], answer: "Indien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/au.png",
      options: ["Australien", "Nya Zeeland", "Storbritannien", "Fiji"], answer: "Australien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/tr.png",
      options: ["Turkiet", "Tunisien", "Pakistan", "Algeriet"], answer: "Turkiet" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/eg.png",
      options: ["Egypten", "Irak", "Jemen", "Syrien"], answer: "Egypten" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/no.png",
      options: ["Norge", "Island", "Danmark", "Finland"], answer: "Norge" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ch.png",
      options: ["Schweiz", "Danmark", "Tonga", "Georgia"], answer: "Schweiz" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ie.png",
      options: ["Irland", "Italien", "Elfenbenskusten", "Indien"], answer: "Irland" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/cu.png",
      options: ["Kuba", "Puerto Rico", "Chile", "Panama"], answer: "Kuba" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/gr.png",
      options: ["Grekland", "Finland", "Israel", "Uruguay"], answer: "Grekland" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ar.png",
      options: ["Argentina", "Uruguay", "Honduras", "Guatemala"], answer: "Argentina" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/th.png",
      options: ["Thailand", "Costa Rica", "Kambodja", "Laos"], answer: "Thailand" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ma.png",
      options: ["Marocko", "Vietnam", "Turkiet", "Kina"], answer: "Marocko" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/pe.png",
      options: ["Peru", "Kanada", "Österrike", "Lettland"], answer: "Peru" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ng.png",
      options: ["Nigeria", "Irland", "Elfenbenskusten", "Indien"], answer: "Nigeria" },

    // === GEOGRAFI (bilder - Unsplash) ===
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=400",
      options: ["Eiffeltornet", "Frihetsgudinnan", "Big Ben", "Pisa lutande torn"], answer: "Eiffeltornet" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400",
      options: ["Colosseum", "Parthenon", "Circus Maximus", "Pantheon"], answer: "Colosseum" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=400",
      options: ["Sydney Operahus", "Walt Disney Concert Hall", "Guggenheim Bilbao", "Lotus Temple"], answer: "Sydney Operahus" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400",
      options: ["Taj Mahal", "Vita Huset", "Buckingham Palace", "Hagia Sophia"], answer: "Taj Mahal" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1526711657229-e7e080ed7aa1?w=400",
      options: ["Kinesiska muren", "Hadrians mur", "Berlins mur", "Västbanksbarriären"], answer: "Kinesiska muren" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "https://images.unsplash.com/photo-1555109307-f7d9da25c244?w=400",
      options: ["Frihetsgudinnan", "Eiffeltornet", "Cristo Redentor", "Big Ben"], answer: "Frihetsgudinnan" },

    // === HISTORIA (bilder - Unsplash) ===
    { category: "Historia", question: "Vilken känd tavla är detta?", image: "https://images.unsplash.com/photo-1423742774270-6884aac775fa?w=400",
      options: ["Mona Lisa", "Venus från Milo", "Flicka med pärlörhänge", "Frida Kahlo"], answer: "Mona Lisa" },
    { category: "Historia", question: "Vilken historisk plats är detta?", image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400",
      options: ["Pyramiderna i Giza", "Machu Picchu", "Stonehenge", "Parthenon"], answer: "Pyramiderna i Giza" },
    { category: "Historia", question: "Vilken historisk plats är detta?", image: "https://images.unsplash.com/photo-1526739178209-77cd5d224e70?w=400",
      options: ["Stonehenge", "Pyramiderna", "Colosseum", "Akropolis"], answer: "Stonehenge" },

    // === VETENSKAP (bilder - Unsplash) ===
    { category: "Vetenskap", question: "Vilken himlakropp är detta?", image: "https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?w=400",
      options: ["Månen", "Merkurius", "Mars", "Pluto"], answer: "Månen" },
    { category: "Vetenskap", question: "Vilken planet är detta?", image: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=400",
      options: ["Saturnus", "Jupiter", "Uranus", "Neptunus"], answer: "Saturnus" },
    { category: "Vetenskap", question: "Vilken planet är detta?", image: "https://images.unsplash.com/photo-1630694093867-4b947d812bf0?w=400",
      options: ["Mars", "Merkurius", "Venus", "Månen"], answer: "Mars" },

    // === MAT (bilder - Unsplash) ===
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
      options: ["Pizza", "Focaccia", "Calzone", "Bruschetta"], answer: "Pizza" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400",
      options: ["Sushi", "Sashimi", "Onigiri", "Maki"], answer: "Sushi" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
      options: ["Hamburgare", "Hot dog", "Smörgås", "Club sandwich"], answer: "Hamburgare" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=400",
      options: ["Pad Thai", "Lo Mein", "Chow Mein", "Yakisoba"], answer: "Pad Thai" },
    { category: "Mat", question: "Vilken bakverk är detta?", image: "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=400",
      options: ["Croissant", "Pain au chocolat", "Brioche", "Danish"], answer: "Croissant" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1534938665420-4c62e6e5e7e1?w=400",
      options: ["Falafel", "Arancini", "Kibbeh", "Croquetas"], answer: "Falafel" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
      options: ["Ramen", "Pho", "Udon", "Tom Yum"], answer: "Ramen" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400",
      options: ["Tacos", "Burrito", "Enchilada", "Quesadilla"], answer: "Tacos" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400",
      options: ["Pasta Carbonara", "Pasta Bolognese", "Pasta Alfredo", "Cacio e Pepe"], answer: "Pasta Carbonara" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400",
      options: ["Paella", "Risotto", "Jambalaya", "Biryani"], answer: "Paella" },
];

const IMAGE_CATEGORIES = [...new Set(IMAGE_QUESTIONS.map(q => q.category))];
