// Image-based questions for all categories
// All images verified visually before inclusion
// Memes + other: local files in img/, Flags: flagcdn (guaranteed correct)

const IMAGE_QUESTIONS = [
    // === MEMES (alla visuellt verifierade mot imgflip ID) ===
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/onedoesnotsimply.jpg",
      options: ["One Does Not Simply", "Boromir Meme", "Lord of the Memes", "Walk Into Mordor", "Sean Bean Says", "You Cannot Simply", "It's Not Easy", "Simply Impossible"],
      answer: "One Does Not Simply" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/drake.jpg",
      options: ["Drake Hotline Bling", "Drake Yes No", "Drake Approves", "Drake Choose", "Hotline Drake", "Drake Pointing", "Drake Decision", "Drake Prefer"],
      answer: "Drake Hotline Bling" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/twobuttons.jpg",
      options: ["Two Buttons", "Daily Struggle", "Hard Choice", "Button Decision", "Sweating Guy", "The Dilemma", "Red Button Meme", "Which Button"],
      answer: "Two Buttons" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/batmanslap.jpg",
      options: ["Batman Slapping Robin", "Batman Smack", "Robin Gets Slapped", "DC Slap", "Holy Slap Batman", "Batman Punch", "Robin Shut Up", "Bat Slap"],
      answer: "Batman Slapping Robin" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/mockingspongebob.jpg",
      options: ["Mocking SpongeBob", "SpongeBob Chicken", "Sarcastic SpongeBob", "tHiS mEmE", "SpongeBob Roast", "Derpy SpongeBob", "Weird SpongeBob", "SpongeBob Sass"],
      answer: "Mocking SpongeBob" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/distractedboyfriend.jpg",
      options: ["Distracted Boyfriend", "Jealous Girlfriend", "Love Triangle", "Guy Looking Back", "Unfaithful Dude", "The Wandering Eye", "Caught Looking", "Boyfriend Meme"],
      answer: "Distracted Boyfriend" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/ancientaliens.jpg",
      options: ["Ancient Aliens", "History Channel Guy", "Aliens Meme", "Giorgio Tsoukalos", "It Was Aliens", "Alien Theory", "History Aliens", "Conspiracy Guy"],
      answer: "Ancient Aliens" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/doge.jpg",
      options: ["Doge", "Shiba Meme", "Much Wow", "Cheems", "Doggo Meme", "Such Meme", "Wow Dog", "Shiba Inu Meme"],
      answer: "Doge" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/waitingskeleton.jpg",
      options: ["Waiting Skeleton", "Skeleton Bench", "Still Waiting", "Dead Waiting", "Skeleton Meme", "Eternal Wait", "Bones on Bench", "Patient Skeleton"],
      answer: "Waiting Skeleton" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/unodraw25.jpg",
      options: ["UNO Draw 25", "Draw 25 Or", "UNO Meme", "Card Game Meme", "UNO Skip", "Draw Cards", "Reverse Card", "UNO Challenge"],
      answer: "UNO Draw 25" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/rollsafe.jpg",
      options: ["Roll Safe", "Thinking Guy", "Smart Move", "Big Brain Time", "Can't Fail If...", "Clever Man", "Hood Think", "The Thinker Meme"],
      answer: "Roll Safe" },
    { category: "Memes", question: "Vad heter denna meme?", image: "img/memes/changemymind.jpg",
      options: ["Change My Mind", "Prove Me Wrong", "Debate Me", "Crowder Meme", "Coffee Debate", "The Table Guy", "Fight Me On This", "Steven Crowder"],
      answer: "Change My Mind" },

    // === FLAGGOR ===
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/jp.png",
      options: ["Japan", "Kina", "Sydkorea", "Bangladesh"], answer: "Japan" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/br.png",
      options: ["Brasilien", "Portugal", "Mexiko", "Argentina"], answer: "Brasilien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ca.png",
      options: ["Kanada", "Peru", "Japan", "Schweiz"], answer: "Kanada" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/za.png",
      options: ["Sydafrika", "Ghana", "Kenya", "Etiopien"], answer: "Sydafrika" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/kr.png",
      options: ["Sydkorea", "Japan", "Taiwan", "Nordkorea"], answer: "Sydkorea" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/mx.png",
      options: ["Mexiko", "Italien", "Irland", "Ungern"], answer: "Mexiko" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/in.png",
      options: ["Indien", "Irland", "Elfenbenskusten", "Niger"], answer: "Indien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/au.png",
      options: ["Australien", "Nya Zeeland", "Storbritannien", "Fiji"], answer: "Australien" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/tr.png",
      options: ["Turkiet", "Tunisien", "Pakistan", "Algeriet"], answer: "Turkiet" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/eg.png",
      options: ["Egypten", "Irak", "Jemen", "Syrien"], answer: "Egypten" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/no.png",
      options: ["Norge", "Island", "Danmark", "Finland"], answer: "Norge" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ch.png",
      options: ["Schweiz", "Danmark", "Tonga", "Georgia"], answer: "Schweiz" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ie.png",
      options: ["Irland", "Italien", "Elfenbenskusten", "Indien"], answer: "Irland" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/cu.png",
      options: ["Kuba", "Puerto Rico", "Chile", "Panama"], answer: "Kuba" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/gr.png",
      options: ["Grekland", "Finland", "Israel", "Uruguay"], answer: "Grekland" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ar.png",
      options: ["Argentina", "Uruguay", "Honduras", "Guatemala"], answer: "Argentina" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/th.png",
      options: ["Thailand", "Costa Rica", "Kambodja", "Laos"], answer: "Thailand" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ma.png",
      options: ["Marocko", "Vietnam", "Turkiet", "Kina"], answer: "Marocko" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/pe.png",
      options: ["Peru", "Kanada", "Österrike", "Lettland"], answer: "Peru" },
    { category: "Flaggor", question: "Vilket land har denna flagga?", image: "https://flagcdn.com/w320/ng.png",
      options: ["Nigeria", "Irland", "Elfenbenskusten", "Indien"], answer: "Nigeria" },

    // === GEOGRAFI (lokala bilder - verifierade) ===
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "img/geografi/eiffeltornet.jpg",
      options: ["Eiffeltornet", "Frihetsgudinnan", "Big Ben", "Pisa lutande torn"], answer: "Eiffeltornet" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "img/geografi/colosseum.jpg",
      options: ["Colosseum", "Parthenon", "Circus Maximus", "Pantheon"], answer: "Colosseum" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "img/geografi/sydney.jpg",
      options: ["Sydney Operahus", "Walt Disney Concert Hall", "Guggenheim Bilbao", "Lotus Temple"], answer: "Sydney Operahus" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "img/geografi/tajmahal.jpg",
      options: ["Taj Mahal", "Vita Huset", "Buckingham Palace", "Hagia Sophia"], answer: "Taj Mahal" },
    { category: "Geografi", question: "Vilken känd byggnad är detta?", image: "img/geografi/kinesiskamuren.jpg",
      options: ["Kinesiska muren", "Hadrians mur", "Berlins mur", "Västbanksbarriären"], answer: "Kinesiska muren" },
    { category: "Geografi", question: "Vilken känd staty är detta?", image: "img/geografi/frihetsgudinnan.jpg",
      options: ["Frihetsgudinnan", "Cristo Redentor", "Manneken Pis", "Lilla Sjöjungfrun"], answer: "Frihetsgudinnan" },

    // === HISTORIA (lokala bilder - verifierade) ===
    { category: "Historia", question: "Vilken historisk plats är detta?", image: "img/historia/pyramiderna.jpg",
      options: ["Pyramiderna i Giza", "Machu Picchu", "Stonehenge", "Parthenon"], answer: "Pyramiderna i Giza" },
    { category: "Historia", question: "Vilken historisk plats är detta?", image: "img/historia/stonehenge.jpg",
      options: ["Stonehenge", "Pyramiderna", "Colosseum", "Akropolis"], answer: "Stonehenge" },

    // === VETENSKAP (lokala bilder - verifierade) ===
    { category: "Vetenskap", question: "Vilken himlakropp är detta?", image: "img/vetenskap/manen.jpg",
      options: ["Månen", "Merkurius", "Mars", "Pluto"], answer: "Månen" },
    { category: "Vetenskap", question: "Vilken planet utforskas här?", image: "img/vetenskap/mars.jpg",
      options: ["Mars", "Månen", "Venus", "Merkurius"], answer: "Mars" },

    // === MAT (lokala bilder - verifierade) ===
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/pizza.jpg",
      options: ["Pizza", "Focaccia", "Calzone", "Bruschetta"], answer: "Pizza" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/sushi.jpg",
      options: ["Sushi", "Sashimi", "Onigiri", "Maki"], answer: "Sushi" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/hamburger.jpg",
      options: ["Hamburgare", "Hot dog", "Smörgås", "Club sandwich"], answer: "Hamburgare" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/ramen.jpg",
      options: ["Ramen", "Pho", "Udon", "Tom Yum"], answer: "Ramen" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/tacos.jpg",
      options: ["Tacos", "Burrito", "Enchilada", "Quesadilla"], answer: "Tacos" },
    { category: "Mat", question: "Vilken bakverk är detta?", image: "img/mat/croissant.jpg",
      options: ["Croissant", "Pain au chocolat", "Brioche", "Danish"], answer: "Croissant" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/padthai.jpg",
      options: ["Pad Thai", "Lo Mein", "Chow Mein", "Yakisoba"], answer: "Pad Thai" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/falafel.jpg",
      options: ["Falafel", "Arancini", "Kibbeh", "Croquetas"], answer: "Falafel" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/carbonara.jpg",
      options: ["Pasta Carbonara", "Pasta Bolognese", "Pasta Alfredo", "Cacio e Pepe"], answer: "Pasta Carbonara" },
    { category: "Mat", question: "Vilken rätt är detta?", image: "img/mat/paella.jpg",
      options: ["Paella", "Risotto", "Jambalaya", "Biryani"], answer: "Paella" },
];

const IMAGE_CATEGORIES = [...new Set(IMAGE_QUESTIONS.map(q => q.category))];
