const QUESTIONS = [
    // === GEOGRAFI ===
    { category: "Geografi", question: "Vad är Frankrikes huvudstad?", options: ["Paris", "Lyon", "Marseille", "Nice"], answer: "Paris" },
    { category: "Geografi", question: "Vilket är världens längsta flod?", options: ["Nilen", "Amazonfloden", "Yangtze", "Mississippi"], answer: "Nilen" },
    { category: "Geografi", question: "I vilket land ligger Machu Picchu?", options: ["Peru", "Bolivia", "Ecuador", "Colombia"], answer: "Peru" },
    { category: "Geografi", question: "Vilken är världens största ö?", options: ["Grönland", "Madagaskar", "Borneo", "Nya Guinea"], answer: "Grönland" },
    { category: "Geografi", question: "Vilket land har flest invånare?", options: ["Indien", "Kina", "USA", "Indonesien"], answer: "Indien" },
    { category: "Geografi", question: "Vad heter Japans högsta berg?", options: ["Fuji", "Kita", "Hotaka", "Aino"], answer: "Fuji" },
    { category: "Geografi", question: "Vilken kontinent är störst till ytan?", options: ["Asien", "Afrika", "Nordamerika", "Europa"], answer: "Asien" },
    { category: "Geografi", question: "I vilket hav ligger Maldiverna?", options: ["Indiska oceanen", "Stilla havet", "Atlanten", "Röda havet"], answer: "Indiska oceanen" },
    { category: "Geografi", question: "Vad är Australiens huvudstad?", options: ["Canberra", "Sydney", "Melbourne", "Brisbane"], answer: "Canberra" },
    { category: "Geografi", question: "Vilket land kallas 'Tusen sjöars land'?", options: ["Finland", "Sverige", "Kanada", "Norge"], answer: "Finland" },
    { category: "Geografi", question: "I vilken stad finns Colosseum?", options: ["Rom", "Aten", "Istanbul", "Kairo"], answer: "Rom" },
    { category: "Geografi", question: "Vilken flod rinner genom London?", options: ["Themsen", "Seine", "Donau", "Rhen"], answer: "Themsen" },

    // === VETENSKAP ===
    { category: "Vetenskap", question: "Vad är det kemiska tecknet för guld?", options: ["Au", "Ag", "Fe", "Cu"], answer: "Au" },
    { category: "Vetenskap", question: "Vilken planet är närmast solen?", options: ["Merkurius", "Venus", "Mars", "Jorden"], answer: "Merkurius" },
    { category: "Vetenskap", question: "Vad mäts i Kelvin?", options: ["Temperatur", "Tryck", "Ljusstyrka", "Elektrisk ström"], answer: "Temperatur" },
    { category: "Vetenskap", question: "Hur många ben har en spindel?", options: ["8", "6", "10", "12"], answer: "8" },
    { category: "Vetenskap", question: "Vad heter det största organet i människokroppen?", options: ["Huden", "Levern", "Hjärnan", "Lungorna"], answer: "Huden" },
    { category: "Vetenskap", question: "Vilken gas andas växter in?", options: ["Koldioxid", "Syre", "Kväve", "Helium"], answer: "Koldioxid" },
    { category: "Vetenskap", question: "Vem formulerade relativitetsteorin?", options: ["Albert Einstein", "Isaac Newton", "Niels Bohr", "Stephen Hawking"], answer: "Albert Einstein" },
    { category: "Vetenskap", question: "Vad heter ljusets hastighet ungefär?", options: ["300 000 km/s", "150 000 km/s", "1 000 000 km/s", "30 000 km/s"], answer: "300 000 km/s" },
    { category: "Vetenskap", question: "Vilken blodtyp kallas universalgivare?", options: ["O-", "AB+", "A+", "B-"], answer: "O-" },
    { category: "Vetenskap", question: "Vad heter vår galax?", options: ["Vintergatan", "Andromeda", "Triangeln", "Virgo"], answer: "Vintergatan" },
    { category: "Vetenskap", question: "Hur många kromosomer har en människa?", options: ["46", "23", "48", "44"], answer: "46" },

    // === SPORT ===
    { category: "Sport", question: "Hur många spelare har ett fotbollslag på plan?", options: ["11", "9", "10", "12"], answer: "11" },
    { category: "Sport", question: "I vilken sport använder man en puck?", options: ["Ishockey", "Bandy", "Lacrosse", "Curling"], answer: "Ishockey" },
    { category: "Sport", question: "Vilket land har vunnit flest fotbolls-VM?", options: ["Brasilien", "Tyskland", "Italien", "Argentina"], answer: "Brasilien" },
    { category: "Sport", question: "Vad heter tennisturneringen i London?", options: ["Wimbledon", "Roland Garros", "US Open", "Australian Open"], answer: "Wimbledon" },
    { category: "Sport", question: "Hur långt är ett maratonlopp?", options: ["42,195 km", "40 km", "45 km", "38,5 km"], answer: "42,195 km" },
    { category: "Sport", question: "Vilket lag vann Champions League 2023?", options: ["Manchester City", "Inter", "Real Madrid", "Bayern München"], answer: "Manchester City" },
    { category: "Sport", question: "I vilken sport är Tiger Woods känd?", options: ["Golf", "Tennis", "Bowling", "Polo"], answer: "Golf" },
    { category: "Sport", question: "Vad heter världens snabbaste man (2009)?", options: ["Usain Bolt", "Tyson Gay", "Carl Lewis", "Yohan Blake"], answer: "Usain Bolt" },
    { category: "Sport", question: "I vilken stad hölls OS 2020?", options: ["Tokyo", "Peking", "Paris", "London"], answer: "Tokyo" },
    { category: "Sport", question: "Hur många poäng ger en touchdown i amerikansk fotboll?", options: ["6", "7", "3", "5"], answer: "6" },
    { category: "Sport", question: "Vad heter Zlatans självbiografi?", options: ["Jag är Zlatan", "Zlatan berättar", "Min historia", "Nummer 10"], answer: "Jag är Zlatan" },
    { category: "Sport", question: "Vilken sport spelar LeBron James?", options: ["Basket", "Amerikansk fotboll", "Baseboll", "Ishockey"], answer: "Basket" },

    // === HISTORIA ===
    { category: "Historia", question: "Vem var den första människan på månen?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], answer: "Neil Armstrong" },
    { category: "Historia", question: "Vad hette skeppet som sjönk 1912?", options: ["Titanic", "Lusitania", "Britannic", "Olympic"], answer: "Titanic" },
    { category: "Historia", question: "Vilken stad bombades med atombomb först?", options: ["Hiroshima", "Nagasaki", "Tokyo", "Osaka"], answer: "Hiroshima" },
    { category: "Historia", question: "Vem målade Mona Lisa?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Botticelli"], answer: "Leonardo da Vinci" },
    { category: "Historia", question: "Vilken mur delade Berlin?", options: ["Berlinmuren", "Kinesiska muren", "Hadrianus mur", "Västmuren"], answer: "Berlinmuren" },
    { category: "Historia", question: "Vem upptäckte Amerika 1492?", options: ["Kristofer Columbus", "Leif Eriksson", "Vasco da Gama", "Marco Polo"], answer: "Kristofer Columbus" },
    { category: "Historia", question: "I vilket land startade den industriella revolutionen?", options: ["England", "Frankrike", "Tyskland", "USA"], answer: "England" },
    { category: "Historia", question: "Vem var Egyptens sista farao?", options: ["Kleopatra", "Nefertiti", "Ramses II", "Tutankhamun"], answer: "Kleopatra" },
    { category: "Historia", question: "Vilket krig pågick 1939-1945?", options: ["Andra världskriget", "Första världskriget", "Koreakriget", "Kalla kriget"], answer: "Andra världskriget" },
    { category: "Historia", question: "Vem skrev 'I Have a Dream'-talet?", options: ["Martin Luther King Jr.", "Malcolm X", "Barack Obama", "Nelson Mandela"], answer: "Martin Luther King Jr." },
    { category: "Historia", question: "Vilket imperium styrde Rom?", options: ["Romerska riket", "Osmanska riket", "Persiska riket", "Bysantinska riket"], answer: "Romerska riket" },
    { category: "Historia", question: "Vilken kung befriade Sverige från Danmark?", options: ["Gustav Vasa", "Karl XII", "Gustav II Adolf", "Erik XIV"], answer: "Gustav Vasa" },

    // === KULTUR & NöJE ===
    { category: "Kultur", question: "Vem skrev Harry Potter?", options: ["J.K. Rowling", "Stephen King", "J.R.R. Tolkien", "Roald Dahl"], answer: "J.K. Rowling" },
    { category: "Kultur", question: "Vilket band sjöng 'Bohemian Rhapsody'?", options: ["Queen", "The Beatles", "Led Zeppelin", "Pink Floyd"], answer: "Queen" },
    { category: "Kultur", question: "Vad heter huvudkaraktären i Breaking Bad?", options: ["Walter White", "Jesse Pinkman", "Hank Schrader", "Saul Goodman"], answer: "Walter White" },
    { category: "Kultur", question: "Vilken Disney-film handlar om en lejon-prins?", options: ["Lejonkungen", "Bambi", "Djungelboken", "Dumbo"], answer: "Lejonkungen" },
    { category: "Kultur", question: "Vem spelar Jack Sparrow?", options: ["Johnny Depp", "Orlando Bloom", "Brad Pitt", "Leonardo DiCaprio"], answer: "Johnny Depp" },
    { category: "Kultur", question: "Vilket band består av fyra killar från Liverpool?", options: ["The Beatles", "The Rolling Stones", "The Who", "Oasis"], answer: "The Beatles" },
    { category: "Kultur", question: "Vad heter trollkarlen i Sagan om Ringen?", options: ["Gandalf", "Saruman", "Dumbledore", "Merlin"], answer: "Gandalf" },
    { category: "Kultur", question: "Vilken artist är känd som 'King of Pop'?", options: ["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"], answer: "Michael Jackson" },
    { category: "Kultur", question: "Vad heter serien med 'Winter is Coming'?", options: ["Game of Thrones", "The Witcher", "Vikings", "Lord of the Rings"], answer: "Game of Thrones" },
    { category: "Kultur", question: "Vilken Pixar-film handlar om känslor i en flickas huvud?", options: ["Insidan ut", "Coco", "Upp", "Wall-E"], answer: "Insidan ut" },
    { category: "Kultur", question: "Vem sjöng 'Rolling in the Deep'?", options: ["Adele", "Beyoncé", "Rihanna", "Taylor Swift"], answer: "Adele" },
    { category: "Kultur", question: "Vad heter den svenska deckaren som skrev Millennium-trilogin?", options: ["Stieg Larsson", "Henning Mankell", "Camilla Läckberg", "Jo Nesbø"], answer: "Stieg Larsson" },

    // === SVERIGE ===
    { category: "Sverige", question: "Vad heter Sveriges längsta flod?", options: ["Klarälven-Göta älv", "Torneälven", "Dalälven", "Umeälven"], answer: "Klarälven-Göta älv" },
    { category: "Sverige", question: "Vilken stad är Sveriges näst största?", options: ["Göteborg", "Malmö", "Uppsala", "Linköping"], answer: "Göteborg" },
    { category: "Sverige", question: "Vem grundade IKEA?", options: ["Ingvar Kamprad", "Erling Persson", "Ruben Rausing", "Hans Rausing"], answer: "Ingvar Kamprad" },
    { category: "Sverige", question: "Vilken dag firas svenska nationaldagen?", options: ["6 juni", "17 maj", "1 maj", "24 december"], answer: "6 juni" },
    { category: "Sverige", question: "Vad heter Sveriges högsta berg?", options: ["Kebnekaise", "Sarek", "Akka", "Sarektjåkkå"], answer: "Kebnekaise" },
    { category: "Sverige", question: "Vem skrev Pippi Långstrump?", options: ["Astrid Lindgren", "Elsa Beskow", "Selma Lagerlöf", "Tove Jansson"], answer: "Astrid Lindgren" },
    { category: "Sverige", question: "Vilken svensk kung regerar idag?", options: ["Carl XVI Gustaf", "Gustaf V", "Karl XII", "Oscar II"], answer: "Carl XVI Gustaf" },
    { category: "Sverige", question: "Vad heter den svenska klockan som firas med dans?", options: ["Midsommar", "Lucia", "Valborg", "Påsk"], answer: "Midsommar" },
    { category: "Sverige", question: "I vilken stad ligger Liseberg?", options: ["Göteborg", "Stockholm", "Malmö", "Linköping"], answer: "Göteborg" },
    { category: "Sverige", question: "Vilket företag grundade Spotify?", options: ["Daniel Ek & Martin Lorentzon", "Niklas Zennström", "Ingvar Kamprad", "Markus Persson"], answer: "Daniel Ek & Martin Lorentzon" },
    { category: "Sverige", question: "Vilken ö är Sveriges största?", options: ["Gotland", "Öland", "Värmdö", "Orust"], answer: "Gotland" },
    { category: "Sverige", question: "Vad heter priset som delas ut i Stockholm varje december?", options: ["Nobelpriset", "Polarpriset", "Augustpriset", "Oscars"], answer: "Nobelpriset" },

    // === SPEL ===
    { category: "Spel", question: "Vem skapade Minecraft?", options: ["Markus 'Notch' Persson", "Shigeru Miyamoto", "Hideo Kojima", "Gabe Newell"], answer: "Markus 'Notch' Persson" },
    { category: "Spel", question: "Vad heter prinsessan som Mario räddar?", options: ["Peach", "Zelda", "Daisy", "Rosalina"], answer: "Peach" },
    { category: "Spel", question: "Vilket spel har en Battle Royale med byggmekanik?", options: ["Fortnite", "PUBG", "Apex Legends", "Call of Duty Warzone"], answer: "Fortnite" },
    { category: "Spel", question: "Vad heter huvudkaraktären i The Legend of Zelda?", options: ["Link", "Zelda", "Ganondorf", "Epona"], answer: "Link" },
    { category: "Spel", question: "Vilket företag gör PlayStation?", options: ["Sony", "Microsoft", "Nintendo", "Sega"], answer: "Sony" },
    { category: "Spel", question: "I vilket spel bygger man med LEGO-liknande block?", options: ["Minecraft", "Roblox", "Terraria", "Lego Worlds"], answer: "Minecraft" },
    { category: "Spel", question: "Vad heter den blåa igelkotten från Sega?", options: ["Sonic", "Shadow", "Knuckles", "Tails"], answer: "Sonic" },
    { category: "Spel", question: "Vilket spel utspelar sig i Night City?", options: ["Cyberpunk 2077", "Watch Dogs", "Deus Ex", "GTA V"], answer: "Cyberpunk 2077" },
    { category: "Spel", question: "Vem är bedragaren i Among Us?", options: ["Impostor", "Crewmate", "Ghost", "Detective"], answer: "Impostor" },
    { category: "Spel", question: "Vilket spel handlar om att fånga monsters i bollar?", options: ["Pokémon", "Digimon", "Monster Hunter", "Yo-Kai Watch"], answer: "Pokémon" },
    { category: "Spel", question: "Vad heter huvudkaraktären i God of War?", options: ["Kratos", "Baldur", "Thor", "Atreus"], answer: "Kratos" },
    { category: "Spel", question: "Vilket bilspel har 'Mario' i titeln?", options: ["Mario Kart", "Mario Racing", "Super Mario Drive", "Mario GP"], answer: "Mario Kart" },

    // === ANIME ===
    { category: "Anime", question: "Vad heter huvudkaraktären i Naruto?", options: ["Naruto Uzumaki", "Sasuke Uchiha", "Kakashi Hatake", "Sakura Haruno"], answer: "Naruto Uzumaki" },
    { category: "Anime", question: "Vad letar Monkey D. Luffy efter i One Piece?", options: ["One Piece (skatten)", "Devil Fruit", "All Blue", "Raftel"], answer: "One Piece (skatten)" },
    { category: "Anime", question: "Vad heter titanen som Eren kan bli i Attack on Titan?", options: ["Attack Titan", "Colossal Titan", "Armored Titan", "Beast Titan"], answer: "Attack Titan" },
    { category: "Anime", question: "Vilken studio gjorde Spirited Away?", options: ["Studio Ghibli", "Toei Animation", "Madhouse", "Bones"], answer: "Studio Ghibli" },
    { category: "Anime", question: "Vad heter dödsboken i Death Note?", options: ["Death Note", "Shinigami Book", "Kira Note", "Black Book"], answer: "Death Note" },
    { category: "Anime", question: "Vem är Gokus rival i Dragon Ball Z?", options: ["Vegeta", "Frieza", "Cell", "Piccolo"], answer: "Vegeta" },
    { category: "Anime", question: "Vad heter demon-dödaren i Demon Slayer?", options: ["Tanjiro Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira", "Giyu Tomioka"], answer: "Tanjiro Kamado" },
    { category: "Anime", question: "Vilken anime har 'Plus Ultra' som motto?", options: ["My Hero Academia", "Black Clover", "Fairy Tail", "One Punch Man"], answer: "My Hero Academia" },
    { category: "Anime", question: "Vad heter Ash Ketchums första Pokémon?", options: ["Pikachu", "Charmander", "Squirtle", "Bulbasaur"], answer: "Pikachu" },
    { category: "Anime", question: "Vem regisserade Your Name?", options: ["Makoto Shinkai", "Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon"], answer: "Makoto Shinkai" },
    { category: "Anime", question: "I vilken anime jagar en pojke demoner för att rädda sin syster?", options: ["Demon Slayer", "Inuyasha", "Blue Exorcist", "Bleach"], answer: "Demon Slayer" },
    { category: "Anime", question: "Vad heter den starkaste hjälten i One Punch Man?", options: ["Saitama", "Genos", "Bang", "King"], answer: "Saitama" },

    // === FILMER ===
    { category: "Filmer", question: "Vem regisserade Titanic och Avatar?", options: ["James Cameron", "Steven Spielberg", "Christopher Nolan", "Peter Jackson"], answer: "James Cameron" },
    { category: "Filmer", question: "Vad heter den magiska stenen i Marvel-filmerna?", options: ["Infinity Stone", "Soul Gem", "Power Crystal", "Cosmic Cube"], answer: "Infinity Stone" },
    { category: "Filmer", question: "Vilken skådespelare spelar Iron Man?", options: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"], answer: "Robert Downey Jr." },
    { category: "Filmer", question: "I vilken film säger man 'May the Force be with you'?", options: ["Star Wars", "Star Trek", "Interstellar", "The Matrix"], answer: "Star Wars" },
    { category: "Filmer", question: "Vad heter den onda AI:n i 2001: A Space Odyssey?", options: ["HAL 9000", "Skynet", "WOPR", "Ultron"], answer: "HAL 9000" },
    { category: "Filmer", question: "Vilken film vann flest Oscars 2024?", options: ["Oppenheimer", "Barbie", "Poor Things", "Killers of the Flower Moon"], answer: "Oppenheimer" },
    { category: "Filmer", question: "Vem spelar Joker i The Dark Knight?", options: ["Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Jared Leto"], answer: "Heath Ledger" },
    { category: "Filmer", question: "Vilken film handlar om drömmar i drömmar?", options: ["Inception", "The Matrix", "Doctor Strange", "Eternal Sunshine"], answer: "Inception" },
    { category: "Filmer", question: "Vad heter fisken som blir hittad i Pixar-filmen?", options: ["Nemo", "Dory", "Marlin", "Gill"], answer: "Nemo" },
    { category: "Filmer", question: "Vilken hobbit bär ringen i Sagan om Ringen?", options: ["Frodo", "Sam", "Bilbo", "Pippin"], answer: "Frodo" },
    { category: "Filmer", question: "Vem spelar Thor i Marvel?", options: ["Chris Hemsworth", "Chris Evans", "Chris Pratt", "Tom Hiddleston"], answer: "Chris Hemsworth" },
    { category: "Filmer", question: "Vilken animerad film sjunger 'Let It Go'?", options: ["Frozen", "Moana", "Tangled", "Encanto"], answer: "Frozen" },

    // === SERIER ===
    { category: "Serier", question: "Vad heter kemiläraren som blir drogkung?", options: ["Walter White", "Jesse Pinkman", "Gus Fring", "Hank Schrader"], answer: "Walter White" },
    { category: "Serier", question: "I vilken serie bor man i Hawkins, Indiana?", options: ["Stranger Things", "The Walking Dead", "Supernatural", "Riverdale"], answer: "Stranger Things" },
    { category: "Serier", question: "Vad heter caféet i Friends?", options: ["Central Perk", "The Coffee Bean", "Starbucks", "Monica's Café"], answer: "Central Perk" },
    { category: "Serier", question: "Vilken serie utspelar sig i Westeros?", options: ["Game of Thrones", "The Witcher", "Lord of the Rings", "Vikings"], answer: "Game of Thrones" },
    { category: "Serier", question: "Vad heter Baby Yodas riktiga namn?", options: ["Grogu", "Din Djarin", "Yoda", "Luke"], answer: "Grogu" },
    { category: "Serier", question: "Vilken gul familj bor i Springfield?", options: ["The Simpsons", "Family Guy", "Bob's Burgers", "American Dad"], answer: "The Simpsons" },
    { category: "Serier", question: "I vilken serie spelar man dödliga barnlekar?", options: ["Squid Game", "Alice in Borderland", "The Hunger Games", "Battle Royale"], answer: "Squid Game" },
    { category: "Serier", question: "Vad jobbar Michael Scott som i The Office?", options: ["Regionchef", "Säljare", "Ekonomichef", "VD"], answer: "Regionchef" },
    { category: "Serier", question: "Vilken serie handlar om en tidresande DeLorean?", options: ["Tillbaka till framtiden", "Doctor Who", "Dark", "Loki"], answer: "Tillbaka till framtiden" },
    { category: "Serier", question: "Vad heter den koreanska serien om överlevnad på Netflix?", options: ["Squid Game", "All of Us Are Dead", "Sweet Home", "Kingdom"], answer: "Squid Game" },
    { category: "Serier", question: "Vilken serie följer familjen Shelby i Birmingham?", options: ["Peaky Blinders", "Downton Abbey", "The Crown", "Taboo"], answer: "Peaky Blinders" },
    { category: "Serier", question: "Vad heter Geralt i The Witcher?", options: ["Geralt av Rivia", "Geralt av Kaer Morhen", "Geralt av Nilfgaard", "Geralt av Cintra"], answer: "Geralt av Rivia" },

    // === MAT ===
    { category: "Mat", question: "Vilket land kommer sushi ursprungligen ifrån?", options: ["Japan", "Kina", "Thailand", "Sydkorea"], answer: "Japan" },
    { category: "Mat", question: "Vad heter den italienska rätten med tunn degbotten, tomatsås och ost?", options: ["Pizza", "Calzone", "Focaccia", "Bruschetta"], answer: "Pizza" },
    { category: "Mat", question: "Vilken krydda ger saffranspannkaka sin gula färg?", options: ["Saffran", "Gurkmeja", "Curry", "Paprika"], answer: "Saffran" },
    { category: "Mat", question: "Vad heter den franska rätten med sniglar?", options: ["Escargot", "Ratatouille", "Bouillabaisse", "Cassoulet"], answer: "Escargot" },
    { category: "Mat", question: "Vilket land är känt för tacos?", options: ["Mexiko", "Spanien", "Argentina", "Brasilien"], answer: "Mexiko" },
    { category: "Mat", question: "Vad heter den japanska soppan med nudlar och buljong?", options: ["Ramen", "Udon", "Soba", "Miso"], answer: "Ramen" },
    { category: "Mat", question: "Vilken frukt kallas 'Kung av frukter' i Sydostasien?", options: ["Durian", "Mango", "Jackfruit", "Papaya"], answer: "Durian" },
    { category: "Mat", question: "Vad heter den indiska rätten med kryddad gryta och ris?", options: ["Biryani", "Tikka Masala", "Vindaloo", "Korma"], answer: "Biryani" },
    { category: "Mat", question: "Vilket land kommer croissanten ursprungligen ifrån?", options: ["Österrike", "Frankrike", "Belgien", "Schweiz"], answer: "Österrike" },
    { category: "Mat", question: "Vad heter den grekiska rätten med aubergine och köttfärs?", options: ["Moussaka", "Gyros", "Souvlaki", "Tzatziki"], answer: "Moussaka" },
    { category: "Mat", question: "Vilken ost har hål i sig?", options: ["Emmentaler", "Gouda", "Brie", "Cheddar"], answer: "Emmentaler" },
    { category: "Mat", question: "Vad är wasabi?", options: ["Japansk pepparrot", "Sjögräs", "Fermenterad soja", "Chili"], answer: "Japansk pepparrot" },
    { category: "Mat", question: "Vilket land kommer kebab ursprungligen ifrån?", options: ["Turkiet", "Libanon", "Irak", "Grekland"], answer: "Turkiet" },
    { category: "Mat", question: "Vad heter Thailands mest kända soppa?", options: ["Tom Yum", "Pad Thai", "Tom Kha", "Som Tam"], answer: "Tom Yum" },
    { category: "Mat", question: "Vilken böna används för att göra choklad?", options: ["Kakaoböna", "Vaniljböna", "Kaffeböna", "Sojaböna"], answer: "Kakaoböna" },
    { category: "Mat", question: "Vad heter den koreanska fermenterade kålen?", options: ["Kimchi", "Sauerkraut", "Tsukemono", "Curtido"], answer: "Kimchi" },
    { category: "Mat", question: "Vilken dryck görs av agave?", options: ["Tequila", "Rum", "Vodka", "Whiskey"], answer: "Tequila" },
    { category: "Mat", question: "Vad heter den italienska deserten med mascarpone och kaffe?", options: ["Tiramisu", "Panna cotta", "Cannoli", "Gelato"], answer: "Tiramisu" },
    { category: "Mat", question: "Vilken frukt är huvudingrediens i guacamole?", options: ["Avokado", "Lime", "Tomat", "Jalapeño"], answer: "Avokado" },
    { category: "Mat", question: "Vad heter det japanska friterade panerade köttet?", options: ["Tonkatsu", "Tempura", "Karaage", "Yakitori"], answer: "Tonkatsu" },

    // === EXTRA GEOGRAFI ===
    { category: "Geografi", question: "Vad heter världens djupaste sjö?", options: ["Bajkalsjön", "Tanganyikasjön", "Kaspiska havet", "Victoriasjön"], answer: "Bajkalsjön" },
    { category: "Geografi", question: "Vilken stad kallas 'Den eviga staden'?", options: ["Rom", "Aten", "Jerusalem", "Kairo"], answer: "Rom" },
    { category: "Geografi", question: "I vilket land ligger Angkor Wat?", options: ["Kambodja", "Thailand", "Vietnam", "Laos"], answer: "Kambodja" },
    { category: "Geografi", question: "Vilken ögrupp tillhör Hawaii?", options: ["USA", "Japan", "Nya Zeeland", "Filippinerna"], answer: "USA" },
    { category: "Geografi", question: "Vad heter sundet mellan Sverige och Danmark?", options: ["Öresund", "Kattegatt", "Skagerrak", "Bälten"], answer: "Öresund" },
    { category: "Geografi", question: "Vilken är Afrikas högsta berg?", options: ["Kilimanjaro", "Mount Kenya", "Ras Dashen", "Mount Meru"], answer: "Kilimanjaro" },

    // === EXTRA VETENSKAP ===
    { category: "Vetenskap", question: "Vad heter den minsta partikeln i ett grundämne?", options: ["Atom", "Molekyl", "Elektron", "Proton"], answer: "Atom" },
    { category: "Vetenskap", question: "Vilken gas utgör mest av jordens atmosfär?", options: ["Kväve", "Syre", "Koldioxid", "Argon"], answer: "Kväve" },
    { category: "Vetenskap", question: "Hur många tänder har en vuxen människa normalt?", options: ["32", "28", "30", "36"], answer: "32" },
    { category: "Vetenskap", question: "Vad heter kroppens största muskel?", options: ["Gluteus maximus", "Quadriceps", "Biceps", "Latissimus dorsi"], answer: "Gluteus maximus" },
    { category: "Vetenskap", question: "Vilken vitamin får man av solljus?", options: ["D-vitamin", "C-vitamin", "A-vitamin", "B12-vitamin"], answer: "D-vitamin" },
    { category: "Vetenskap", question: "Vad är H2O?", options: ["Vatten", "Väteperoxid", "Saltsyra", "Kolsyra"], answer: "Vatten" },

    // === EXTRA SPORT ===
    { category: "Sport", question: "Vilket land har vunnit flest OS-guld totalt?", options: ["USA", "Kina", "Ryssland", "Storbritannien"], answer: "USA" },
    { category: "Sport", question: "Vad heter den mest prestigefyllda cykeltävlingen?", options: ["Tour de France", "Giro d'Italia", "Vuelta a España", "Paris-Roubaix"], answer: "Tour de France" },
    { category: "Sport", question: "Hur många hål spelas i en runda golf?", options: ["18", "9", "12", "16"], answer: "18" },
    { category: "Sport", question: "Vilken sport kallas 'The Beautiful Game'?", options: ["Fotboll", "Tennis", "Basket", "Cricket"], answer: "Fotboll" },
    { category: "Sport", question: "Vem har flest Grand Slam-titlar i herrtennis?", options: ["Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"], answer: "Novak Djokovic" },
    { category: "Sport", question: "I vilken sport tävlar man i octagon?", options: ["MMA", "Boxning", "Brottning", "Judo"], answer: "MMA" },

    // === EXTRA HISTORIA ===
    { category: "Historia", question: "Vilken civilisation byggde Machu Picchu?", options: ["Inkariket", "Aztekerna", "Mayafolket", "Olmekerna"], answer: "Inkariket" },
    { category: "Historia", question: "Vad hette den sista drottningen av Frankrike före revolutionen?", options: ["Marie Antoinette", "Marie de Medici", "Catherine de Medici", "Josephine"], answer: "Marie Antoinette" },
    { category: "Historia", question: "Vilket år föll Berlinmuren?", options: ["1989", "1991", "1987", "1990"], answer: "1989" },
    { category: "Historia", question: "Vem var Romarrikets mest kände diktator?", options: ["Julius Caesar", "Augustus", "Nero", "Caligula"], answer: "Julius Caesar" },
    { category: "Historia", question: "Vilken uppfinning revolutionerade kommunikation 1876?", options: ["Telefonen", "Telegrafen", "Radion", "Televisionen"], answer: "Telefonen" },
    { category: "Historia", question: "Vad hette det kalla krigets rymdkapplöning?", options: ["Space Race", "Star Wars", "Apollo Project", "Sputnik Race"], answer: "Space Race" },

    // === EXTRA KULTUR ===
    { category: "Kultur", question: "Vilken konstnär klippte av sitt öra?", options: ["Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Salvador Dalí"], answer: "Vincent van Gogh" },
    { category: "Kultur", question: "Vad heter den mest sålda boken genom tiderna?", options: ["Bibeln", "Don Quijote", "Harry Potter", "Sagan om Ringen"], answer: "Bibeln" },
    { category: "Kultur", question: "Vilken artist har sålt flest album i historien?", options: ["Elvis Presley", "Michael Jackson", "The Beatles", "Elton John"], answer: "Elvis Presley" },
    { category: "Kultur", question: "Vad heter den japanska serietidningsgenren?", options: ["Manga", "Manhwa", "Manhua", "Anime"], answer: "Manga" },
    { category: "Kultur", question: "Vilken app är känd för korta dansvideor?", options: ["TikTok", "Instagram", "Snapchat", "YouTube Shorts"], answer: "TikTok" },
    { category: "Kultur", question: "Vem skrev Romeo och Julia?", options: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Oscar Wilde"], answer: "William Shakespeare" },

    // === EXTRA SVERIGE ===
    { category: "Sverige", question: "Vilken svensk stad kallas 'Norrlands huvudstad'?", options: ["Umeå", "Sundsvall", "Luleå", "Gävle"], answer: "Umeå" },
    { category: "Sverige", question: "Vad heter Sveriges äldsta stad?", options: ["Sigtuna", "Uppsala", "Birka", "Lund"], answer: "Sigtuna" },
    { category: "Sverige", question: "Vilken svensk uppfann dynamiten?", options: ["Alfred Nobel", "Gustaf Dalén", "Baltzar von Platen", "Nils Bohlin"], answer: "Alfred Nobel" },
    { category: "Sverige", question: "Vad heter den svenska glassbaren som grundades i Eslöv?", options: ["GB Glace", "SIA Glass", "Triumf Glass", "Hemglass"], answer: "GB Glace" },
    { category: "Sverige", question: "Vilken svensk artist sjöng 'Sommartider'?", options: ["Gyllene Tider", "Roxette", "ABBA", "Europe"], answer: "Gyllene Tider" },
    { category: "Sverige", question: "Hur många landskap har Sverige?", options: ["25", "21", "24", "28"], answer: "25" },

    // === EXTRA SPEL ===
    { category: "Spel", question: "Vilket spel utspelar sig i Hyrule?", options: ["The Legend of Zelda", "Final Fantasy", "Dark Souls", "Dragon Quest"], answer: "The Legend of Zelda" },
    { category: "Spel", question: "Vad heter skaparen av Metal Gear Solid?", options: ["Hideo Kojima", "Shigeru Miyamoto", "Hidetaka Miyazaki", "Yu Suzuki"], answer: "Hideo Kojima" },
    { category: "Spel", question: "Vilket spel har 'The Nether' som dimension?", options: ["Minecraft", "Terraria", "Roblox", "Valheim"], answer: "Minecraft" },
    { category: "Spel", question: "Vad heter det populära kortspelet med Uno-regler?", options: ["Uno", "Skip-Bo", "Phase 10", "Dos"], answer: "Uno" },
    { category: "Spel", question: "Vilket bilspel utvecklas av Polyphony Digital?", options: ["Gran Turismo", "Forza", "Need for Speed", "Project Cars"], answer: "Gran Turismo" },
    { category: "Spel", question: "Vad heter bossen i varje Zelda-spel?", options: ["Ganon", "Bowser", "Sephiroth", "Ridley"], answer: "Ganon" },

    // === EXTRA ANIME ===
    { category: "Anime", question: "Vilken anime handlar om en anteckningsbok som dödar?", options: ["Death Note", "Tokyo Ghoul", "Parasyte", "Another"], answer: "Death Note" },
    { category: "Anime", question: "Vad heter piratbåten i One Piece?", options: ["Thousand Sunny", "Going Merry", "Red Force", "Moby Dick"], answer: "Thousand Sunny" },
    { category: "Anime", question: "Vilken anime har 'Bankai' som kraft?", options: ["Bleach", "Naruto", "Dragon Ball", "One Piece"], answer: "Bleach" },
    { category: "Anime", question: "Vem är känd som 'Hero for Fun'?", options: ["Saitama", "Goku", "All Might", "Naruto"], answer: "Saitama" },
    { category: "Anime", question: "Vilken anime utspelar sig i en värld av titaner?", options: ["Attack on Titan", "Claymore", "Berserk", "God Eater"], answer: "Attack on Titan" },
    { category: "Anime", question: "Vad heter Gokus mest kända attack?", options: ["Kamehameha", "Spirit Bomb", "Final Flash", "Rasengan"], answer: "Kamehameha" },

    // === EXTRA FILMER ===
    { category: "Filmer", question: "Vilken film vann första Oscar för bästa film?", options: ["Wings", "Sunrise", "The Jazz Singer", "Ben-Hur"], answer: "Wings" },
    { category: "Filmer", question: "Vem regisserade Jurassic Park?", options: ["Steven Spielberg", "James Cameron", "Ridley Scott", "George Lucas"], answer: "Steven Spielberg" },
    { category: "Filmer", question: "Vilken film har citatet 'I see dead people'?", options: ["The Sixth Sense", "The Others", "Ghost", "Poltergeist"], answer: "The Sixth Sense" },
    { category: "Filmer", question: "Vad heter AI:n i filmen Her?", options: ["Samantha", "Alexa", "Siri", "Cortana"], answer: "Samantha" },
    { category: "Filmer", question: "Vilken Disney-film utspelar sig i Colombia?", options: ["Encanto", "Coco", "Moana", "Luca"], answer: "Encanto" },
    { category: "Filmer", question: "Vem spelar Wolverine i X-Men?", options: ["Hugh Jackman", "Ryan Reynolds", "Chris Evans", "Robert Downey Jr."], answer: "Hugh Jackman" },

    // === EXTRA SERIER ===
    { category: "Serier", question: "Vilken serie handlar om en mexikansk drogkartell?", options: ["Narcos", "Breaking Bad", "Ozark", "Queen of the South"], answer: "Narcos" },
    { category: "Serier", question: "Vad heter familjen i Succession?", options: ["Roy", "Murdoch", "Redstone", "Trump"], answer: "Roy" },
    { category: "Serier", question: "Vilken serie utspelar sig i ett dystopiskt Gilead?", options: ["The Handmaid's Tale", "Westworld", "Black Mirror", "The 100"], answer: "The Handmaid's Tale" },
    { category: "Serier", question: "Vad heter barnserien med en blå katt och en guldfisk?", options: ["Gumball", "SpongeBob", "Adventure Time", "Regular Show"], answer: "Gumball" },
    { category: "Serier", question: "Vilken serie följer en tidresenär i en telefonkiosk?", options: ["Doctor Who", "Dark", "Loki", "Quantum Leap"], answer: "Doctor Who" },
    { category: "Serier", question: "Vad heter dokumentärserien om Tiger King?", options: ["Tiger King", "Wild Wild Country", "Making a Murderer", "The Jinx"], answer: "Tiger King" },

    // === SVÅRA FRÅGOR (6 alternativ = difficulty 2) ===
    { category: "Geografi", question: "Vad heter huvudstaden i Myanmar?", options: ["Naypyidaw", "Rangoon", "Mandalay", "Bangkok", "Vientiane", "Phnom Penh"], answer: "Naypyidaw" },
    { category: "Geografi", question: "Vilken är världens minsta land till ytan?", options: ["Vatikanstaten", "Monaco", "San Marino", "Liechtenstein", "Malta", "Andorra"], answer: "Vatikanstaten" },
    { category: "Geografi", question: "Genom hur många länder rinner Donau?", options: ["10", "7", "8", "12", "6", "9"], answer: "10" },
    { category: "Vetenskap", question: "Vad heter det kemiska tecknet för kvicksilver?", options: ["Hg", "Qs", "Kv", "Mg", "Ag", "Pb"], answer: "Hg" },
    { category: "Vetenskap", question: "Vilken är den hårdaste mineralen på Mohs skala?", options: ["Diamant", "Korund", "Topas", "Kvarts", "Rubin", "Safir"], answer: "Diamant" },
    { category: "Vetenskap", question: "Hur många hjärtrum har ett krokodilhjärta?", options: ["4", "2", "3", "5", "1", "6"], answer: "4" },
    { category: "Sport", question: "Hur många perioder spelas i en ishockeymatch?", options: ["3", "2", "4", "5", "6", "Halvlekar"], answer: "3" },
    { category: "Sport", question: "Vilken fotbollsspelare kallas 'El Pibe de Oro'?", options: ["Maradona", "Pelé", "Messi", "Ronaldo", "Neymar", "Zidane"], answer: "Maradona" },
    { category: "Historia", question: "Vilken kejsare byggde Kinas terrakottaarmé?", options: ["Qin Shi Huang", "Liu Bang", "Wu Zetian", "Kangxi", "Kublai Khan", "Genghis Khan"], answer: "Qin Shi Huang" },
    { category: "Historia", question: "Vilket år grundades FN?", options: ["1945", "1948", "1942", "1950", "1939", "1946"], answer: "1945" },
    { category: "Kultur", question: "Vem skrev 1984?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Franz Kafka", "H.G. Wells", "Arthur C. Clarke"], answer: "George Orwell" },
    { category: "Kultur", question: "Vilken konstnär är känd för 'Stjärnenatten'?", options: ["Vincent van Gogh", "Claude Monet", "Edvard Munch", "Pablo Picasso", "Salvador Dalí", "Gustav Klimt"], answer: "Vincent van Gogh" },
    { category: "Sverige", question: "Vilken svensk stad har Sveriges äldsta universitet?", options: ["Uppsala", "Lund", "Stockholm", "Göteborg", "Linköping", "Umeå"], answer: "Uppsala" },
    { category: "Spel", question: "Vilket företag utvecklade Dark Souls?", options: ["FromSoftware", "Capcom", "Konami", "Bandai Namco", "Square Enix", "CD Projekt"], answer: "FromSoftware" },
    { category: "Anime", question: "Vilken Ghibli-film handlar om en flicka i en andevärld?", options: ["Spirited Away", "Princess Mononoke", "Howl's Moving Castle", "My Neighbor Totoro", "Ponyo", "Kiki's Delivery Service"], answer: "Spirited Away" },
    { category: "Filmer", question: "Vilken regissör är känd för 'plot twists' som i The Sixth Sense?", options: ["M. Night Shyamalan", "Christopher Nolan", "David Fincher", "Denis Villeneuve", "Darren Aronofsky", "Jordan Peele"], answer: "M. Night Shyamalan" },
    { category: "Serier", question: "Vilken serie handlar om en koreansk överlevnadstävling med barnlekar?", options: ["Squid Game", "Alice in Borderland", "All of Us Are Dead", "Sweet Home", "Kingdom", "Hellbound"], answer: "Squid Game" },
    { category: "Mat", question: "Vilken ört används traditionellt i pesto?", options: ["Basilika", "Oregano", "Persilja", "Koriander", "Timjan", "Rosmarin"], answer: "Basilika" },

    // === MYCKET SVÅRA FRÅGOR (8 alternativ = difficulty 3) ===
    { category: "Geografi", question: "Vad heter huvudstaden i Burkina Faso?", options: ["Ouagadougou", "Bamako", "Niamey", "Lomé", "Accra", "Abidjan", "Dakar", "Conakry"], answer: "Ouagadougou" },
    { category: "Geografi", question: "Vilken sjö är Afrikas största?", options: ["Victoriasjön", "Tanganyikasjön", "Malawisjön", "Turkanasjön", "Albertsjön", "Nassasjön", "Chadsjön", "Kivusjön"], answer: "Victoriasjön" },
    { category: "Vetenskap", question: "Vad heter det tyngsta naturliga grundämnet?", options: ["Uran", "Plutonium", "Bly", "Guld", "Kvicksilver", "Osmium", "Wolfram", "Radium"], answer: "Uran" },
    { category: "Vetenskap", question: "Vilken är den vanligaste blodtypen i världen?", options: ["O+", "A+", "B+", "AB+", "O-", "A-", "B-", "AB-"], answer: "O+" },
    { category: "Sport", question: "Vilken nation har flest VM-titlar i cricket?", options: ["Australien", "Indien", "England", "Västindien", "Pakistan", "Sri Lanka", "Sydafrika", "Nya Zeeland"], answer: "Australien" },
    { category: "Sport", question: "Vem vann Ballon d'Or flest gånger?", options: ["Lionel Messi", "Cristiano Ronaldo", "Johan Cruyff", "Michel Platini", "Marco van Basten", "Zinedine Zidane", "Ronaldo Nazário", "Luka Modrić"], answer: "Lionel Messi" },
    { category: "Historia", question: "Vilken dynasti styrde Kina längst?", options: ["Zhou-dynastin", "Han-dynastin", "Tang-dynastin", "Ming-dynastin", "Qing-dynastin", "Song-dynastin", "Sui-dynastin", "Yuan-dynastin"], answer: "Zhou-dynastin" },
    { category: "Historia", question: "Vilket slag anses vara Napoleon's slutgiltiga nederlag?", options: ["Waterloo", "Leipzig", "Austerlitz", "Borodino", "Trafalgar", "Jena", "Wagram", "Marengo"], answer: "Waterloo" },
    { category: "Kultur", question: "Vilken författare skrev 'Hundra år av ensamhet'?", options: ["Gabriel García Márquez", "Isabel Allende", "Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda", "Julio Cortázar", "Carlos Fuentes", "Octavio Paz"], answer: "Gabriel García Márquez" },
    { category: "Sverige", question: "Vilken svensk vetenskapsman uppfann Celsiusskalan?", options: ["Anders Celsius", "Carl von Linné", "Emanuel Swedenborg", "Jöns Jacob Berzelius", "Alfred Nobel", "Svante Arrhenius", "Ångström", "Scheele"], answer: "Anders Celsius" },
    { category: "Spel", question: "Vilket år släpptes det allra första The Legend of Zelda?", options: ["1986", "1985", "1987", "1988", "1984", "1989", "1990", "1983"], answer: "1986" },
    { category: "Anime", question: "Vilken mangaka skapade One Piece?", options: ["Eiichiro Oda", "Masashi Kishimoto", "Akira Toriyama", "Tite Kubo", "Hajime Isayama", "Yoshihiro Togashi", "Hiromu Arakawa", "Takehiko Inoue"], answer: "Eiichiro Oda" },
    { category: "Filmer", question: "Vilken film har den högsta intjäningen genom tiderna (oinflationsjusterat)?", options: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens", "Avengers: Infinity War", "Spider-Man: No Way Home", "Jurassic World", "The Lion King"], answer: "Avatar" },
    { category: "Serier", question: "Vilken showrunner skapade Breaking Bad?", options: ["Vince Gilligan", "David Chase", "Shonda Rhimes", "Ryan Murphy", "David Simon", "Matthew Weiner", "Damon Lindelof", "Sam Esmail"], answer: "Vince Gilligan" },
    { category: "Mat", question: "Vilken peppar mäts högst på Scoville-skalan?", options: ["Carolina Reaper", "Trinidad Scorpion", "Ghost Pepper", "Habanero", "Jalapeño", "Cayenne", "Scotch Bonnet", "Thai Chili"], answer: "Carolina Reaper" },
];

const CATEGORIES = [...new Set([...QUESTIONS.map(q => q.category), ...IMAGE_CATEGORIES])];
