// Karaktärsdata för Gissa Namnet!
// Pokémon: de 101 första från originalserien (Kanto, #001-#101)
// Bilder: PokeAPI official artwork (raw.githubusercontent.com/PokeAPI/sprites)
// Naruto: kända karaktärer med bilder från Naruto-wikin (static.wikia.nocookie.net)

const POKEMON_101 = [
    { id: 1, name: "Bulbasaur" },
    { id: 2, name: "Ivysaur" },
    { id: 3, name: "Venusaur" },
    { id: 4, name: "Charmander" },
    { id: 5, name: "Charmeleon" },
    { id: 6, name: "Charizard" },
    { id: 7, name: "Squirtle" },
    { id: 8, name: "Wartortle" },
    { id: 9, name: "Blastoise" },
    { id: 10, name: "Caterpie" },
    { id: 11, name: "Metapod" },
    { id: 12, name: "Butterfree" },
    { id: 13, name: "Weedle" },
    { id: 14, name: "Kakuna" },
    { id: 15, name: "Beedrill" },
    { id: 16, name: "Pidgey" },
    { id: 17, name: "Pidgeotto" },
    { id: 18, name: "Pidgeot" },
    { id: 19, name: "Rattata" },
    { id: 20, name: "Raticate" },
    { id: 21, name: "Spearow" },
    { id: 22, name: "Fearow" },
    { id: 23, name: "Ekans" },
    { id: 24, name: "Arbok" },
    { id: 25, name: "Pikachu" },
    { id: 26, name: "Raichu" },
    { id: 27, name: "Sandshrew" },
    { id: 28, name: "Sandslash" },
    { id: 29, name: "Nidoran ♀" },
    { id: 30, name: "Nidorina" },
    { id: 31, name: "Nidoqueen" },
    { id: 32, name: "Nidoran ♂" },
    { id: 33, name: "Nidorino" },
    { id: 34, name: "Nidoking" },
    { id: 35, name: "Clefairy" },
    { id: 36, name: "Clefable" },
    { id: 37, name: "Vulpix" },
    { id: 38, name: "Ninetales" },
    { id: 39, name: "Jigglypuff" },
    { id: 40, name: "Wigglytuff" },
    { id: 41, name: "Zubat" },
    { id: 42, name: "Golbat" },
    { id: 43, name: "Oddish" },
    { id: 44, name: "Gloom" },
    { id: 45, name: "Vileplume" },
    { id: 46, name: "Paras" },
    { id: 47, name: "Parasect" },
    { id: 48, name: "Venonat" },
    { id: 49, name: "Venomoth" },
    { id: 50, name: "Diglett" },
    { id: 51, name: "Dugtrio" },
    { id: 52, name: "Meowth" },
    { id: 53, name: "Persian" },
    { id: 54, name: "Psyduck" },
    { id: 55, name: "Golduck" },
    { id: 56, name: "Mankey" },
    { id: 57, name: "Primeape" },
    { id: 58, name: "Growlithe" },
    { id: 59, name: "Arcanine" },
    { id: 60, name: "Poliwag" },
    { id: 61, name: "Poliwhirl" },
    { id: 62, name: "Poliwrath" },
    { id: 63, name: "Abra" },
    { id: 64, name: "Kadabra" },
    { id: 65, name: "Alakazam" },
    { id: 66, name: "Machop" },
    { id: 67, name: "Machoke" },
    { id: 68, name: "Machamp" },
    { id: 69, name: "Bellsprout" },
    { id: 70, name: "Weepinbell" },
    { id: 71, name: "Victreebel" },
    { id: 72, name: "Tentacool" },
    { id: 73, name: "Tentacruel" },
    { id: 74, name: "Geodude" },
    { id: 75, name: "Graveler" },
    { id: 76, name: "Golem" },
    { id: 77, name: "Ponyta" },
    { id: 78, name: "Rapidash" },
    { id: 79, name: "Slowpoke" },
    { id: 80, name: "Slowbro" },
    { id: 81, name: "Magnemite" },
    { id: 82, name: "Magneton" },
    { id: 83, name: "Farfetch'd" },
    { id: 84, name: "Doduo" },
    { id: 85, name: "Dodrio" },
    { id: 86, name: "Seel" },
    { id: 87, name: "Dewgong" },
    { id: 88, name: "Grimer" },
    { id: 89, name: "Muk" },
    { id: 90, name: "Shellder" },
    { id: 91, name: "Cloyster" },
    { id: 92, name: "Gastly" },
    { id: 93, name: "Haunter" },
    { id: 94, name: "Gengar" },
    { id: 95, name: "Onix" },
    { id: 96, name: "Drowzee" },
    { id: 97, name: "Hypno" },
    { id: 98, name: "Krabby" },
    { id: 99, name: "Kingler" },
    { id: 100, name: "Voltorb" },
    { id: 101, name: "Electrode" }
];

const NARUTO_CHARS = [
    { id: "naruto", name: "Naruto Uzumaki", img: "https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png" },
    { id: "sasuke", name: "Sasuke Uchiha", img: "https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png" },
    { id: "sakura", name: "Sakura Haruno", img: "https://static.wikia.nocookie.net/naruto/images/6/64/Sakura_Part_1.png" },
    { id: "kakashi", name: "Kakashi Hatake", img: "https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png" },
    { id: "itachi", name: "Itachi Uchiha", img: "https://static.wikia.nocookie.net/naruto/images/b/bb/Itachi.png" },
    { id: "gaara", name: "Gaara", img: "https://static.wikia.nocookie.net/naruto/images/2/20/Gaara_in_Part_I.png" },
    { id: "rocklee", name: "Rock Lee", img: "https://static.wikia.nocookie.net/naruto/images/9/97/Rock_Lee_Part_I.png" },
    { id: "hinata", name: "Hinata Hyuga", img: "https://static.wikia.nocookie.net/naruto/images/9/97/Hinata.png" },
    { id: "neji", name: "Neji Hyuga", img: "https://static.wikia.nocookie.net/naruto/images/7/7e/Neji_Part_I.png" },
    { id: "shikamaru", name: "Shikamaru Nara", img: "https://static.wikia.nocookie.net/naruto/images/4/44/Shikamaru_Part_I.png" },
    { id: "jiraiya", name: "Jiraiya", img: "https://static.wikia.nocookie.net/naruto/images/1/1f/Jiraiya_Young.png" },
    { id: "tsunade", name: "Tsunade", img: "https://static.wikia.nocookie.net/naruto/images/b/b3/Tsunade_infobox2.png" },
    { id: "orochimaru", name: "Orochimaru", img: "https://static.wikia.nocookie.net/naruto/images/1/14/Orochimaru_Infobox.png" },
    { id: "guy", name: "Might Guy", img: "https://static.wikia.nocookie.net/naruto/images/3/31/Might_Guy.png" },
    { id: "iruka", name: "Iruka Umino", img: "https://static.wikia.nocookie.net/naruto/images/b/bc/Iruka.png" },
    { id: "ino", name: "Ino Yamanaka", img: "https://static.wikia.nocookie.net/naruto/images/d/dd/Ino.png" },
    { id: "choji", name: "Choji Akimichi", img: "https://static.wikia.nocookie.net/naruto/images/7/7d/Ch%C5%8Dji_Akimichi.png" },
    { id: "kiba", name: "Kiba Inuzuka", img: "https://static.wikia.nocookie.net/naruto/images/0/03/Kiba.png" },
    { id: "shino", name: "Shino Aburame", img: "https://static.wikia.nocookie.net/naruto/images/9/9c/Shino.png" },
    { id: "tenten", name: "Tenten", img: "https://static.wikia.nocookie.net/naruto/images/d/da/Tenten_Part_1.png" },
    { id: "minato", name: "Minato Namikaze", img: "https://static.wikia.nocookie.net/naruto/images/7/71/Minato_Namikaze.png" },
    { id: "kisame", name: "Kisame Hoshigaki", img: "https://static.wikia.nocookie.net/naruto/images/2/25/Kisame.png" },
    { id: "deidara", name: "Deidara", img: "https://static.wikia.nocookie.net/naruto/images/0/06/Deidara.png" },
    { id: "konan", name: "Konan", img: "https://static.wikia.nocookie.net/naruto/images/5/58/Konan_Infobox.png" },
    { id: "kabuto", name: "Kabuto Yakushi", img: "https://static.wikia.nocookie.net/naruto/images/c/c9/Kabuto_Part_1.png" },
    { id: "zabuza", name: "Zabuza Momochi", img: "https://static.wikia.nocookie.net/naruto/images/3/37/Zabuza_Momochi.png" },
    { id: "haku", name: "Haku", img: "https://static.wikia.nocookie.net/naruto/images/9/90/Haku.png" },
    { id: "killerbee", name: "Killer Bee", img: "https://static.wikia.nocookie.net/naruto/images/6/63/Killer_B.png" },
    { id: "temari", name: "Temari", img: "https://static.wikia.nocookie.net/naruto/images/b/bb/Temari_newshot.png" },
    { id: "kankuro", name: "Kankuro", img: "https://static.wikia.nocookie.net/naruto/images/7/7d/Kankur%C5%8D1.png" },
    { id: "asuma", name: "Asuma Sarutobi", img: "https://static.wikia.nocookie.net/naruto/images/7/7c/Asuma.png" },
    { id: "kurenai", name: "Kurenai Yuhi", img: "https://static.wikia.nocookie.net/naruto/images/6/67/Kurenai_Part_I.png" },
    { id: "hiruzen", name: "Hiruzen Sarutobi", img: "https://static.wikia.nocookie.net/naruto/images/e/e4/Hiruzen_Sarutobi.png" },
    { id: "obito", name: "Obito Uchiha", img: "https://static.wikia.nocookie.net/naruto/images/4/4a/Obito_Uchiha.png" },
    { id: "madara", name: "Madara Uchiha", img: "https://static.wikia.nocookie.net/naruto/images/f/fd/Madara.png" },
    { id: "sai", name: "Sai", img: "https://static.wikia.nocookie.net/naruto/images/0/07/Sai_Infobox.png" },
    { id: "yamato", name: "Yamato", img: "https://static.wikia.nocookie.net/naruto/images/f/f7/Yamato_newshot.png" },
    { id: "nagato", name: "Nagato (Pain)", img: "https://static.wikia.nocookie.net/naruto/images/4/46/Nagato.png" },
    { id: "konohamaru", name: "Konohamaru Sarutobi", img: "https://static.wikia.nocookie.net/naruto/images/8/89/Konohamaru_p1.png" },
    { id: "shizune", name: "Shizune", img: "https://static.wikia.nocookie.net/naruto/images/0/0a/Shizune_Infobox.png" },
    { id: "anko", name: "Anko Mitarashi", img: "https://static.wikia.nocookie.net/naruto/images/b/bd/Anko_Part_I.png" },
    { id: "hidan", name: "Hidan", img: "https://static.wikia.nocookie.net/naruto/images/e/e3/Hidan.png" },
    { id: "sasori", name: "Sasori", img: "https://static.wikia.nocookie.net/naruto/images/f/f7/Sasori.png" }
];
